;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; IO
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; Syntax:
;;
;;   (read-delimited-string port)
;;
      read-generic-in-range-prompt
      read-real-in-range
      read-integer-in-range
      read-object-generic-list
      read-object-generic
      read-object-id/name-list
      read-object-id/name
      read-string-from-list
      read-symbol-from-list
      read-symbol-list
      read-symbol
      yes-or-no?
      y-or-n?
      read-string/symbol-list
      read-string-list
      read-boolean-list
      read-real-list
      read-integer-list
      read-filename
      read-symbol/string
      read-string/symbol
      read-string
      read-real
      read-positive-integer
      read-integer
      ti-read-unquoted-string
      read-generic-list-prompt
      read-generic-prompt
      read-real-pair-list
      real-pair?
      read-generic-list-pair
      read-generic-list
      read-generic
      readq-generic